apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: {{ printf "rd-%s" .Release.Name | trunc 20 }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app: {{ printf "rd-%s" .Release.Name  | trunc 20 }}
spec:
  ports:
  - port: {{ .Values.service.Port }}
    name: {{ .Values.service.name }}
  clusterIP: None
  selector:
    app: {{ printf "rd-%s" .Release.Name  | trunc 20}}