apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "fullname" . }}
spec:
  selector:
    matchLabels:
      app: {{ template "fullname" . }}
  minAvailable: {{ .Values.replicaCount }}